#include "OverlayRenderer.hpp"

#include <renderer/ExternalRenderContext.hpp>

#include <QVulkanWindow>
#include <QVulkanInstance>
#include <QImage>
#include <QtDebug>

#include <algorithm>
#include <cstring>

// SPIR-V byte arrays generated by glslangValidator at build time (see the
// overlay-shader rules in CMakeLists.txt). No runtime file loading.
#include "overlay_shaders/grid_vert.h"
#include "overlay_shaders/grid_frag.h"
#include "overlay_shaders/gizmo_vert.h"
#include "overlay_shaders/gizmo_frag.h"

namespace vkview {

namespace {

// Push constants shared by the grid shaders; must match grid.frag's PC block
struct GridPushConstants {
    glm::vec4 camPosFov;      // xyz camera position, w tan(fovY/2)
    glm::vec4 forwardAspect;  // xyz forward, w aspect
    glm::vec4 rightAlpha;     // xyz right, w overall grid alpha
    glm::vec4 upPad;          // xyz up, w orthographic film height (0 = perspective)
};
static_assert(sizeof(GridPushConstants) == 64, "GridPushConstants size mismatch");

VkShaderModule createShaderModule(VkDevice device, const uint32_t* code, size_t bytes) {
    VkShaderModuleCreateInfo info{};
    info.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    info.codeSize = bytes;
    info.pCode = code;
    VkShaderModule module = VK_NULL_HANDLE;
    if (vkCreateShaderModule(device, &info, nullptr, &module) != VK_SUCCESS) {
        qWarning() << "OverlayRenderer: failed to create shader module";
    }
    return module;
}

uint32_t findMemoryType(VkPhysicalDevice physDevice, uint32_t typeBits,
                        VkMemoryPropertyFlags props) {
    VkPhysicalDeviceMemoryProperties memProps;
    vkGetPhysicalDeviceMemoryProperties(physDevice, &memProps);
    for (uint32_t i = 0; i < memProps.memoryTypeCount; ++i) {
        if ((typeBits & (1u << i)) &&
            (memProps.memoryTypes[i].propertyFlags & props) == props) {
            return i;
        }
    }
    return 0;
}

}  // namespace

void OverlayRenderer::record(QVulkanWindow* window,
                             quantiloom::ExternalRenderContext* ctx,
                             VkCommandBuffer cmd,
                             uint32_t width, uint32_t height,
                             const CameraMatrices& camera,
                             const std::vector<editing::GizmoVertex>& gizmoVertices) {
    const bool drawGizmo = !gizmoVertices.empty();
    if ((!m_gridVisible && !drawGizmo) || !ctx || width == 0 || height == 0) {
        return;  // nothing composited: leave the SDK's PRESENT_SRC frame alone
    }

    ensureStaticResources(window);
    if (m_gridPipeline == VK_NULL_HANDLE || m_gizmoPipeline == VK_NULL_HANDLE) {
        return;
    }
    ensureSizedResources(window, cmd, width, height);
    ensureGizmoBuffers(window);

    // 1. Pull the primary-hit depth into our sampled image
    ctx->BlitDepthTo(cmd, m_depthAov.image, m_depthAovLayout, width, height);
    m_depthAovLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;

    // Upload this frame's gizmo triangles into the frame's own buffer (the
    // previous frame may still be reading its buffer on the GPU)
    uint32_t gizmoVertexCount = 0;
    FrameVertexBuffer* gizmoVbo = nullptr;
    if (drawGizmo && !m_gizmoVertexBuffers.empty()) {
        const int frame = window->currentFrame();
        gizmoVbo = &m_gizmoVertexBuffers[static_cast<size_t>(frame) %
                                         m_gizmoVertexBuffers.size()];
        const VkDeviceSize bytes = gizmoVertices.size() * sizeof(editing::GizmoVertex);
        if (gizmoVbo->mapped && bytes <= gizmoVbo->capacity) {
            std::memcpy(gizmoVbo->mapped, gizmoVertices.data(), bytes);
            gizmoVertexCount = static_cast<uint32_t>(gizmoVertices.size());
        } else if (bytes > gizmoVbo->capacity) {
            qWarning() << "OverlayRenderer: gizmo geometry exceeds buffer capacity";
        }
    }

    // 2. The SDK left the swapchain image in PRESENT_SRC; make it a color
    //    attachment again
    const int swapIndex = window->currentSwapChainImageIndex();
    VkImage swapImage = window->swapChainImage(swapIndex);
    VkImageView swapView = window->swapChainImageView(swapIndex);

    VkImageMemoryBarrier toColor{};
    toColor.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
    toColor.oldLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
    toColor.newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    toColor.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    toColor.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    toColor.image = swapImage;
    toColor.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    toColor.subresourceRange.levelCount = 1;
    toColor.subresourceRange.layerCount = 1;
    toColor.srcAccessMask = 0;  // the SDK's own barrier made the blit available
    toColor.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT |
                            VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                         VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT, 0,
                         0, nullptr, 0, nullptr, 1, &toColor);

    // 3. Dynamic rendering over the existing frame
    VkRenderingAttachmentInfoKHR colorAttachment{};
    colorAttachment.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO_KHR;
    colorAttachment.imageView = swapView;
    colorAttachment.imageLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    colorAttachment.loadOp = VK_ATTACHMENT_LOAD_OP_LOAD;  // never clear the frame
    colorAttachment.storeOp = VK_ATTACHMENT_STORE_OP_STORE;

    VkRenderingAttachmentInfoKHR depthAttachment{};
    depthAttachment.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO_KHR;
    depthAttachment.imageView = m_overlayDepth.view;
    depthAttachment.imageLayout = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL;
    depthAttachment.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;  // overlay-only depth
    depthAttachment.storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    depthAttachment.clearValue.depthStencil = {1.0f, 0};

    VkRenderingInfoKHR renderingInfo{};
    renderingInfo.sType = VK_STRUCTURE_TYPE_RENDERING_INFO_KHR;
    renderingInfo.renderArea = {{0, 0}, {width, height}};
    renderingInfo.layerCount = 1;
    renderingInfo.colorAttachmentCount = 1;
    renderingInfo.pColorAttachments = &colorAttachment;
    renderingInfo.pDepthAttachment = &depthAttachment;

    m_vkCmdBeginRendering(cmd, &renderingInfo);

    VkViewport viewport{0.0f, 0.0f, static_cast<float>(width),
                        static_cast<float>(height), 0.0f, 1.0f};
    VkRect2D scissor{{0, 0}, {width, height}};
    vkCmdSetViewport(cmd, 0, 1, &viewport);
    vkCmdSetScissor(cmd, 0, 1, &scissor);

    if (m_gridVisible) {
        GridPushConstants pc{};
        pc.camPosFov = glm::vec4(camera.position(), camera.fovScale());
        pc.forwardAspect = glm::vec4(camera.forward(), camera.aspect());
        pc.rightAlpha = glm::vec4(camera.right(), 0.55f);
        // A positive height is what tells the shader to use orthographic
        // rays; perspective passes zero, as the padding always did.
        pc.upPad = glm::vec4(camera.up(),
                             camera.orthographic() ? camera.orthoHeight() : 0.0f);

        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, m_gridPipeline);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS,
                                m_gridPipelineLayout, 0, 1, &m_descriptorSet,
                                0, nullptr);
        vkCmdPushConstants(cmd, m_gridPipelineLayout,
                           VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                           0, sizeof(pc), &pc);
        vkCmdDraw(cmd, 3, 1, 0, 0);  // fullscreen triangle, no vertex buffer
    }

    if (gizmoVertexCount > 0 && gizmoVbo) {
        const glm::mat4 viewProj = camera.viewProj();
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, m_gizmoPipeline);
        vkCmdPushConstants(cmd, m_gizmoPipelineLayout, VK_SHADER_STAGE_VERTEX_BIT,
                           0, sizeof(viewProj), &viewProj);
        const VkDeviceSize offset = 0;
        vkCmdBindVertexBuffers(cmd, 0, 1, &gizmoVbo->buffer, &offset);
        vkCmdDraw(cmd, gizmoVertexCount, 1, 0, 0);
    }

    m_vkCmdEndRendering(cmd);

    // 4. Back to PRESENT_SRC for Qt's present
    VkImageMemoryBarrier toPresent = toColor;
    toPresent.oldLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    toPresent.newLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
    toPresent.srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    toPresent.dstAccessMask = 0;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
                         VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, 0,
                         0, nullptr, 0, nullptr, 1, &toPresent);
}

void OverlayRenderer::ensureStaticResources(QVulkanWindow* window) {
    const VkFormat colorFormat = window->colorFormat();
    if (m_staticReady && colorFormat == m_pipelineColorFormat) {
        return;
    }

    VkDevice device = window->device();

    if (!m_vkCmdBeginRendering) {
        auto load = [&](const char* khr, const char* core) {
            auto fn = vkGetDeviceProcAddr(device, khr);
            if (!fn) fn = vkGetDeviceProcAddr(device, core);
            return fn;
        };
        m_vkCmdBeginRendering = reinterpret_cast<PFN_vkCmdBeginRenderingKHR>(
            load("vkCmdBeginRenderingKHR", "vkCmdBeginRendering"));
        m_vkCmdEndRendering = reinterpret_cast<PFN_vkCmdEndRenderingKHR>(
            load("vkCmdEndRenderingKHR", "vkCmdEndRendering"));
        if (!m_vkCmdBeginRendering || !m_vkCmdEndRendering) {
            qWarning() << "OverlayRenderer: dynamic rendering entry points missing";
            return;
        }
    }

    if (m_nearestSampler == VK_NULL_HANDLE) {
        // NEAREST on purpose: depth must never be bilinearly mixed across
        // silhouettes
        VkSamplerCreateInfo samplerInfo{};
        samplerInfo.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
        samplerInfo.magFilter = VK_FILTER_NEAREST;
        samplerInfo.minFilter = VK_FILTER_NEAREST;
        samplerInfo.addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
        samplerInfo.addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
        samplerInfo.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
        vkCreateSampler(device, &samplerInfo, nullptr, &m_nearestSampler);
    }

    if (m_descriptorSetLayout == VK_NULL_HANDLE) {
        VkDescriptorSetLayoutBinding binding{};
        binding.binding = 0;
        binding.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        binding.descriptorCount = 1;
        binding.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;

        VkDescriptorSetLayoutCreateInfo layoutInfo{};
        layoutInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
        layoutInfo.bindingCount = 1;
        layoutInfo.pBindings = &binding;
        vkCreateDescriptorSetLayout(device, &layoutInfo, nullptr, &m_descriptorSetLayout);

        VkDescriptorPoolSize poolSize{VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1};
        VkDescriptorPoolCreateInfo poolInfo{};
        poolInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
        poolInfo.poolSizeCount = 1;
        poolInfo.pPoolSizes = &poolSize;
        poolInfo.maxSets = 1;
        vkCreateDescriptorPool(device, &poolInfo, nullptr, &m_descriptorPool);

        VkDescriptorSetAllocateInfo allocInfo{};
        allocInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
        allocInfo.descriptorPool = m_descriptorPool;
        allocInfo.descriptorSetCount = 1;
        allocInfo.pSetLayouts = &m_descriptorSetLayout;
        vkAllocateDescriptorSets(device, &allocInfo, &m_descriptorSet);
    }

    createGridPipeline(window, colorFormat);
    createGizmoPipeline(window, colorFormat);
    m_pipelineColorFormat = colorFormat;
    m_staticReady = true;
}

void OverlayRenderer::createGizmoPipeline(QVulkanWindow* window, VkFormat colorFormat) {
    VkDevice device = window->device();

    if (m_gizmoPipeline != VK_NULL_HANDLE) {
        vkDestroyPipeline(device, m_gizmoPipeline, nullptr);
        m_gizmoPipeline = VK_NULL_HANDLE;
    }

    if (m_gizmoPipelineLayout == VK_NULL_HANDLE) {
        VkPushConstantRange pushRange{};
        pushRange.stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
        pushRange.size = sizeof(glm::mat4);  // viewProj

        VkPipelineLayoutCreateInfo layoutInfo{};
        layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
        layoutInfo.pushConstantRangeCount = 1;
        layoutInfo.pPushConstantRanges = &pushRange;
        vkCreatePipelineLayout(device, &layoutInfo, nullptr, &m_gizmoPipelineLayout);
    }

    VkShaderModule vertModule =
        createShaderModule(device, kGizmoVertSpv, sizeof(kGizmoVertSpv));
    VkShaderModule fragModule =
        createShaderModule(device, kGizmoFragSpv, sizeof(kGizmoFragSpv));
    if (vertModule == VK_NULL_HANDLE || fragModule == VK_NULL_HANDLE) {
        return;
    }

    VkPipelineShaderStageCreateInfo stages[2]{};
    stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vertModule;
    stages[0].pName = "main";
    stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = fragModule;
    stages[1].pName = "main";

    VkVertexInputBindingDescription binding{};
    binding.binding = 0;
    binding.stride = sizeof(editing::GizmoVertex);
    binding.inputRate = VK_VERTEX_INPUT_RATE_VERTEX;

    VkVertexInputAttributeDescription attributes[2]{};
    attributes[0].location = 0;
    attributes[0].format = VK_FORMAT_R32G32B32_SFLOAT;
    attributes[0].offset = offsetof(editing::GizmoVertex, position);
    attributes[1].location = 1;
    attributes[1].format = VK_FORMAT_R32G32B32A32_SFLOAT;
    attributes[1].offset = offsetof(editing::GizmoVertex, color);

    VkPipelineVertexInputStateCreateInfo vertexInput{};
    vertexInput.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
    vertexInput.vertexBindingDescriptionCount = 1;
    vertexInput.pVertexBindingDescriptions = &binding;
    vertexInput.vertexAttributeDescriptionCount = 2;
    vertexInput.pVertexAttributeDescriptions = attributes;

    VkPipelineInputAssemblyStateCreateInfo inputAssembly{};
    inputAssembly.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    inputAssembly.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

    VkPipelineViewportStateCreateInfo viewportState{};
    viewportState.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    viewportState.viewportCount = 1;
    viewportState.scissorCount = 1;

    // No culling: handles must read from every side, including ring backs
    VkPipelineRasterizationStateCreateInfo raster{};
    raster.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    raster.polygonMode = VK_POLYGON_MODE_FILL;
    raster.cullMode = VK_CULL_MODE_NONE;
    raster.lineWidth = 1.0f;

    VkPipelineMultisampleStateCreateInfo multisample{};
    multisample.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    multisample.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    // Depth on, against the overlay's just-cleared attachment: the gizmo
    // always covers scene and grid, and occludes itself correctly
    VkPipelineDepthStencilStateCreateInfo depthStencil{};
    depthStencil.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
    depthStencil.depthTestEnable = VK_TRUE;
    depthStencil.depthWriteEnable = VK_TRUE;
    depthStencil.depthCompareOp = VK_COMPARE_OP_LESS_OR_EQUAL;

    VkPipelineColorBlendAttachmentState blendAttachment{};
    blendAttachment.blendEnable = VK_TRUE;
    blendAttachment.srcColorBlendFactor = VK_BLEND_FACTOR_SRC_ALPHA;
    blendAttachment.dstColorBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
    blendAttachment.colorBlendOp = VK_BLEND_OP_ADD;
    blendAttachment.srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
    blendAttachment.dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
    blendAttachment.alphaBlendOp = VK_BLEND_OP_ADD;
    blendAttachment.colorWriteMask =
        VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
        VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;

    VkPipelineColorBlendStateCreateInfo blend{};
    blend.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    blend.attachmentCount = 1;
    blend.pAttachments = &blendAttachment;

    const VkDynamicState dynamicStates[] = {VK_DYNAMIC_STATE_VIEWPORT,
                                            VK_DYNAMIC_STATE_SCISSOR};
    VkPipelineDynamicStateCreateInfo dynamic{};
    dynamic.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    dynamic.dynamicStateCount = 2;
    dynamic.pDynamicStates = dynamicStates;

    VkPipelineRenderingCreateInfoKHR rendering{};
    rendering.sType = VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO_KHR;
    rendering.colorAttachmentCount = 1;
    rendering.pColorAttachmentFormats = &colorFormat;
    rendering.depthAttachmentFormat = VK_FORMAT_D32_SFLOAT;

    VkGraphicsPipelineCreateInfo pipelineInfo{};
    pipelineInfo.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    pipelineInfo.pNext = &rendering;
    pipelineInfo.stageCount = 2;
    pipelineInfo.pStages = stages;
    pipelineInfo.pVertexInputState = &vertexInput;
    pipelineInfo.pInputAssemblyState = &inputAssembly;
    pipelineInfo.pViewportState = &viewportState;
    pipelineInfo.pRasterizationState = &raster;
    pipelineInfo.pMultisampleState = &multisample;
    pipelineInfo.pDepthStencilState = &depthStencil;
    pipelineInfo.pColorBlendState = &blend;
    pipelineInfo.pDynamicState = &dynamic;
    pipelineInfo.layout = m_gizmoPipelineLayout;

    if (vkCreateGraphicsPipelines(device, VK_NULL_HANDLE, 1, &pipelineInfo,
                                  nullptr, &m_gizmoPipeline) != VK_SUCCESS) {
        qWarning() << "OverlayRenderer: failed to create gizmo pipeline";
        m_gizmoPipeline = VK_NULL_HANDLE;
    }

    vkDestroyShaderModule(device, vertModule, nullptr);
    vkDestroyShaderModule(device, fragModule, nullptr);
}

void OverlayRenderer::ensureGizmoBuffers(QVulkanWindow* window) {
    if (!m_gizmoVertexBuffers.empty()) {
        return;
    }
    VkDevice device = window->device();
    const int frames = std::max(window->concurrentFrameCount(), 1);
    // Largest handle set is well under 1000 triangles; 64 KiB has headroom
    constexpr VkDeviceSize kCapacity = 64 * 1024;

    m_gizmoVertexBuffers.resize(static_cast<size_t>(frames));
    for (auto& vbo : m_gizmoVertexBuffers) {
        VkBufferCreateInfo bufferInfo{};
        bufferInfo.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
        bufferInfo.size = kCapacity;
        bufferInfo.usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
        bufferInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
        if (vkCreateBuffer(device, &bufferInfo, nullptr, &vbo.buffer) != VK_SUCCESS) {
            qWarning() << "OverlayRenderer: failed to create gizmo vertex buffer";
            continue;
        }

        VkMemoryRequirements memReq;
        vkGetBufferMemoryRequirements(device, vbo.buffer, &memReq);
        VkMemoryAllocateInfo allocInfo{};
        allocInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
        allocInfo.allocationSize = memReq.size;
        allocInfo.memoryTypeIndex =
            findMemoryType(window->physicalDevice(), memReq.memoryTypeBits,
                           VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                               VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
        if (vkAllocateMemory(device, &allocInfo, nullptr, &vbo.memory) != VK_SUCCESS ||
            vkBindBufferMemory(device, vbo.buffer, vbo.memory, 0) != VK_SUCCESS ||
            vkMapMemory(device, vbo.memory, 0, kCapacity, 0, &vbo.mapped) != VK_SUCCESS) {
            qWarning() << "OverlayRenderer: failed to allocate gizmo vertex memory";
            continue;
        }
        vbo.capacity = kCapacity;
    }
}

void OverlayRenderer::destroyGizmoBuffers(VkDevice device) {
    for (auto& vbo : m_gizmoVertexBuffers) {
        if (vbo.mapped) vkUnmapMemory(device, vbo.memory);
        if (vbo.buffer != VK_NULL_HANDLE) vkDestroyBuffer(device, vbo.buffer, nullptr);
        if (vbo.memory != VK_NULL_HANDLE) vkFreeMemory(device, vbo.memory, nullptr);
    }
    m_gizmoVertexBuffers.clear();
}

void OverlayRenderer::createGridPipeline(QVulkanWindow* window, VkFormat colorFormat) {
    VkDevice device = window->device();

    if (m_gridPipeline != VK_NULL_HANDLE) {
        vkDestroyPipeline(device, m_gridPipeline, nullptr);
        m_gridPipeline = VK_NULL_HANDLE;
    }

    if (m_gridPipelineLayout == VK_NULL_HANDLE) {
        VkPushConstantRange pushRange{};
        pushRange.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
        pushRange.size = sizeof(GridPushConstants);

        VkPipelineLayoutCreateInfo layoutInfo{};
        layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
        layoutInfo.setLayoutCount = 1;
        layoutInfo.pSetLayouts = &m_descriptorSetLayout;
        layoutInfo.pushConstantRangeCount = 1;
        layoutInfo.pPushConstantRanges = &pushRange;
        vkCreatePipelineLayout(device, &layoutInfo, nullptr, &m_gridPipelineLayout);
    }

    VkShaderModule vertModule =
        createShaderModule(device, kGridVertSpv, sizeof(kGridVertSpv));
    VkShaderModule fragModule =
        createShaderModule(device, kGridFragSpv, sizeof(kGridFragSpv));
    if (vertModule == VK_NULL_HANDLE || fragModule == VK_NULL_HANDLE) {
        return;
    }

    VkPipelineShaderStageCreateInfo stages[2]{};
    stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vertModule;
    stages[0].pName = "main";
    stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = fragModule;
    stages[1].pName = "main";

    VkPipelineVertexInputStateCreateInfo vertexInput{};
    vertexInput.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;

    VkPipelineInputAssemblyStateCreateInfo inputAssembly{};
    inputAssembly.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    inputAssembly.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

    VkPipelineViewportStateCreateInfo viewportState{};
    viewportState.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    viewportState.viewportCount = 1;
    viewportState.scissorCount = 1;

    VkPipelineRasterizationStateCreateInfo raster{};
    raster.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    raster.polygonMode = VK_POLYGON_MODE_FILL;
    raster.cullMode = VK_CULL_MODE_NONE;
    raster.lineWidth = 1.0f;

    VkPipelineMultisampleStateCreateInfo multisample{};
    multisample.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    multisample.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    // Grid ignores raster depth entirely: occlusion by the scene happens in
    // the fragment shader against the depth AOV, and the gizmo drawn after it
    // always covers it (the overlay depth was just cleared).
    VkPipelineDepthStencilStateCreateInfo depthStencil{};
    depthStencil.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
    depthStencil.depthTestEnable = VK_FALSE;
    depthStencil.depthWriteEnable = VK_FALSE;

    VkPipelineColorBlendAttachmentState blendAttachment{};
    blendAttachment.blendEnable = VK_TRUE;
    blendAttachment.srcColorBlendFactor = VK_BLEND_FACTOR_SRC_ALPHA;
    blendAttachment.dstColorBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
    blendAttachment.colorBlendOp = VK_BLEND_OP_ADD;
    blendAttachment.srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
    blendAttachment.dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
    blendAttachment.alphaBlendOp = VK_BLEND_OP_ADD;
    blendAttachment.colorWriteMask =
        VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
        VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;

    VkPipelineColorBlendStateCreateInfo blend{};
    blend.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    blend.attachmentCount = 1;
    blend.pAttachments = &blendAttachment;

    const VkDynamicState dynamicStates[] = {VK_DYNAMIC_STATE_VIEWPORT,
                                            VK_DYNAMIC_STATE_SCISSOR};
    VkPipelineDynamicStateCreateInfo dynamic{};
    dynamic.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    dynamic.dynamicStateCount = 2;
    dynamic.pDynamicStates = dynamicStates;

    VkPipelineRenderingCreateInfoKHR rendering{};
    rendering.sType = VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO_KHR;
    rendering.colorAttachmentCount = 1;
    rendering.pColorAttachmentFormats = &colorFormat;
    rendering.depthAttachmentFormat = VK_FORMAT_D32_SFLOAT;

    VkGraphicsPipelineCreateInfo pipelineInfo{};
    pipelineInfo.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    pipelineInfo.pNext = &rendering;
    pipelineInfo.stageCount = 2;
    pipelineInfo.pStages = stages;
    pipelineInfo.pVertexInputState = &vertexInput;
    pipelineInfo.pInputAssemblyState = &inputAssembly;
    pipelineInfo.pViewportState = &viewportState;
    pipelineInfo.pRasterizationState = &raster;
    pipelineInfo.pMultisampleState = &multisample;
    pipelineInfo.pDepthStencilState = &depthStencil;
    pipelineInfo.pColorBlendState = &blend;
    pipelineInfo.pDynamicState = &dynamic;
    pipelineInfo.layout = m_gridPipelineLayout;

    if (vkCreateGraphicsPipelines(device, VK_NULL_HANDLE, 1, &pipelineInfo,
                                  nullptr, &m_gridPipeline) != VK_SUCCESS) {
        qWarning() << "OverlayRenderer: failed to create grid pipeline";
        m_gridPipeline = VK_NULL_HANDLE;
    }

    vkDestroyShaderModule(device, vertModule, nullptr);
    vkDestroyShaderModule(device, fragModule, nullptr);
}

void OverlayRenderer::ensureSizedResources(QVulkanWindow* window, VkCommandBuffer cmd,
                                           uint32_t width, uint32_t height) {
    VkDevice device = window->device();

    if (m_depthAov.width != width || m_depthAov.height != height) {
        destroyImage(device, m_depthAov);
        m_depthAov = createImage(window, width, height, VK_FORMAT_R32_SFLOAT,
                                 VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT,
                                 VK_IMAGE_ASPECT_COLOR_BIT);
        m_depthAovLayout = VK_IMAGE_LAYOUT_UNDEFINED;

        VkDescriptorImageInfo imageInfo{};
        imageInfo.sampler = m_nearestSampler;
        imageInfo.imageView = m_depthAov.view;
        imageInfo.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;

        VkWriteDescriptorSet write{};
        write.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        write.dstSet = m_descriptorSet;
        write.dstBinding = 0;
        write.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        write.descriptorCount = 1;
        write.pImageInfo = &imageInfo;
        vkUpdateDescriptorSets(device, 1, &write, 0, nullptr);
    }

    if (m_overlayDepth.width != width || m_overlayDepth.height != height) {
        destroyImage(device, m_overlayDepth);
        m_overlayDepth = createImage(window, width, height, VK_FORMAT_D32_SFLOAT,
                                     VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT,
                                     VK_IMAGE_ASPECT_DEPTH_BIT);
    }

    // Every frame, not just the first: frames overlap on the GPU, and the
    // clear at the top of this frame's pass must not race the depth writes
    // of the previous one. oldLayout UNDEFINED on purpose -- the attachment
    // is cleared anyway, so last frame's contents are discardable, and the
    // barrier is then purely an execution dependency on prior depth use.
    {
        VkImageMemoryBarrier toDepth{};
        toDepth.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
        toDepth.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        toDepth.newLayout = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL;
        toDepth.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        toDepth.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        toDepth.image = m_overlayDepth.image;
        toDepth.subresourceRange.aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT;
        toDepth.subresourceRange.levelCount = 1;
        toDepth.subresourceRange.layerCount = 1;
        toDepth.srcAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
        toDepth.dstAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT |
                                VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
        vkCmdPipelineBarrier(cmd,
                             VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT |
                                 VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT,
                             VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT |
                                 VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT,
                             0, 0, nullptr, 0, nullptr, 1, &toDepth);
    }
}

OverlayRenderer::OwnedImage OverlayRenderer::createImage(
    QVulkanWindow* window, uint32_t width, uint32_t height, VkFormat format,
    VkImageUsageFlags usage, VkImageAspectFlags aspect) {
    VkDevice device = window->device();
    OwnedImage img;
    img.width = width;
    img.height = height;

    VkImageCreateInfo imageInfo{};
    imageInfo.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    imageInfo.imageType = VK_IMAGE_TYPE_2D;
    imageInfo.format = format;
    imageInfo.extent = {width, height, 1};
    imageInfo.mipLevels = 1;
    imageInfo.arrayLayers = 1;
    imageInfo.samples = VK_SAMPLE_COUNT_1_BIT;
    imageInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
    imageInfo.usage = usage;
    if (vkCreateImage(device, &imageInfo, nullptr, &img.image) != VK_SUCCESS) {
        qWarning() << "OverlayRenderer: failed to create image";
        return img;
    }

    VkMemoryRequirements memReq;
    vkGetImageMemoryRequirements(device, img.image, &memReq);
    VkMemoryAllocateInfo allocInfo{};
    allocInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    allocInfo.allocationSize = memReq.size;
    allocInfo.memoryTypeIndex = findMemoryType(window->physicalDevice(),
                                               memReq.memoryTypeBits,
                                               VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (vkAllocateMemory(device, &allocInfo, nullptr, &img.memory) != VK_SUCCESS ||
        vkBindImageMemory(device, img.image, img.memory, 0) != VK_SUCCESS) {
        qWarning() << "OverlayRenderer: failed to allocate image memory";
        destroyImage(device, img);
        return img;
    }

    VkImageViewCreateInfo viewInfo{};
    viewInfo.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    viewInfo.image = img.image;
    viewInfo.viewType = VK_IMAGE_VIEW_TYPE_2D;
    viewInfo.format = format;
    viewInfo.subresourceRange.aspectMask = aspect;
    viewInfo.subresourceRange.levelCount = 1;
    viewInfo.subresourceRange.layerCount = 1;
    if (vkCreateImageView(device, &viewInfo, nullptr, &img.view) != VK_SUCCESS) {
        qWarning() << "OverlayRenderer: failed to create image view";
        destroyImage(device, img);
    }
    return img;
}

void OverlayRenderer::destroyImage(VkDevice device, OwnedImage& img) {
    if (img.view != VK_NULL_HANDLE) vkDestroyImageView(device, img.view, nullptr);
    if (img.image != VK_NULL_HANDLE) vkDestroyImage(device, img.image, nullptr);
    if (img.memory != VK_NULL_HANDLE) vkFreeMemory(device, img.memory, nullptr);
    img = OwnedImage{};
}

void OverlayRenderer::requestCompositedCapture(const QString& path) {
    if (!m_capturePath.isEmpty()) {
        return;  // one at a time; the pending one wins
    }
    m_capturePath = path;
    m_captureRecorded = false;
}

void OverlayRenderer::recordCaptureIfRequested(QVulkanWindow* window,
                                               VkCommandBuffer cmd,
                                               uint32_t width, uint32_t height) {
    if (m_capturePath.isEmpty() || m_captureRecorded || width == 0 || height == 0) {
        return;
    }
    VkDevice device = window->device();

    destroyCaptureBuffer(device);
    const VkDeviceSize bytes = VkDeviceSize(width) * height * 4;
    VkBufferCreateInfo bufferInfo{};
    bufferInfo.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    bufferInfo.size = bytes;
    bufferInfo.usage = VK_BUFFER_USAGE_TRANSFER_DST_BIT;
    bufferInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateBuffer(device, &bufferInfo, nullptr, &m_captureBuffer) != VK_SUCCESS) {
        qWarning() << "OverlayRenderer: capture buffer creation failed";
        m_capturePath.clear();
        return;
    }
    VkMemoryRequirements memReq;
    vkGetBufferMemoryRequirements(device, m_captureBuffer, &memReq);
    VkMemoryAllocateInfo allocInfo{};
    allocInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    allocInfo.allocationSize = memReq.size;
    allocInfo.memoryTypeIndex =
        findMemoryType(window->physicalDevice(), memReq.memoryTypeBits,
                       VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                           VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    if (vkAllocateMemory(device, &allocInfo, nullptr, &m_captureMemory) != VK_SUCCESS ||
        vkBindBufferMemory(device, m_captureBuffer, m_captureMemory, 0) != VK_SUCCESS ||
        vkMapMemory(device, m_captureMemory, 0, bytes, 0, &m_captureMapped) != VK_SUCCESS) {
        qWarning() << "OverlayRenderer: capture buffer memory failed";
        destroyCaptureBuffer(device);
        m_capturePath.clear();
        return;
    }

    const int swapIndex = window->currentSwapChainImageIndex();
    VkImage swapImage = window->swapChainImage(swapIndex);

    VkImageMemoryBarrier toSrc{};
    toSrc.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
    toSrc.oldLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
    toSrc.newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
    toSrc.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    toSrc.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    toSrc.image = swapImage;
    toSrc.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    toSrc.subresourceRange.levelCount = 1;
    toSrc.subresourceRange.layerCount = 1;
    toSrc.srcAccessMask = VK_ACCESS_MEMORY_WRITE_BIT;
    toSrc.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
                         VK_PIPELINE_STAGE_TRANSFER_BIT, 0,
                         0, nullptr, 0, nullptr, 1, &toSrc);

    VkBufferImageCopy region{};
    region.imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    region.imageSubresource.layerCount = 1;
    region.imageExtent = {width, height, 1};
    vkCmdCopyImageToBuffer(cmd, swapImage, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                           m_captureBuffer, 1, &region);

    VkImageMemoryBarrier toPresent = toSrc;
    toPresent.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
    toPresent.newLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
    toPresent.srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
    toPresent.dstAccessMask = 0;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                         VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, 0,
                         0, nullptr, 0, nullptr, 1, &toPresent);

    m_captureWidth = width;
    m_captureHeight = height;
    m_captureFormat = window->colorFormat();
    m_captureRecorded = true;
    // The copy is provably complete once every frame in flight has cycled
    m_captureCountdown = window->concurrentFrameCount() + 1;
}

void OverlayRenderer::finishCaptureIfReady(QVulkanWindow* window) {
    if (!m_captureRecorded || m_captureMapped == nullptr) {
        return;
    }
    if (--m_captureCountdown > 0) {
        return;
    }

    const QImage::Format format =
        (m_captureFormat == VK_FORMAT_R8G8B8A8_SRGB ||
         m_captureFormat == VK_FORMAT_R8G8B8A8_UNORM)
            ? QImage::Format_RGBA8888
            : QImage::Format_ARGB32;  // B8G8R8A8 bytes are ARGB32 little-endian
    const QImage view(static_cast<const uchar*>(m_captureMapped),
                      static_cast<int>(m_captureWidth),
                      static_cast<int>(m_captureHeight),
                      static_cast<qsizetype>(m_captureWidth) * 4, format);
    const bool saved = view.copy().save(m_capturePath, "PNG");
    if (saved) {
        qInfo() << "OverlayRenderer: composited capture saved to" << m_capturePath;
    } else {
        qWarning() << "OverlayRenderer: failed to save composited capture to"
                   << m_capturePath;
    }

    destroyCaptureBuffer(window->device());
    m_capturePath.clear();
    m_captureRecorded = false;
}

void OverlayRenderer::destroyCaptureBuffer(VkDevice device) {
    if (m_captureMapped) {
        vkUnmapMemory(device, m_captureMemory);
        m_captureMapped = nullptr;
    }
    if (m_captureBuffer != VK_NULL_HANDLE) {
        vkDestroyBuffer(device, m_captureBuffer, nullptr);
        m_captureBuffer = VK_NULL_HANDLE;
    }
    if (m_captureMemory != VK_NULL_HANDLE) {
        vkFreeMemory(device, m_captureMemory, nullptr);
        m_captureMemory = VK_NULL_HANDLE;
    }
}

void OverlayRenderer::releaseResources(QVulkanWindow* window) {
    VkDevice device = window->device();
    if (device == VK_NULL_HANDLE) {
        return;
    }
    vkDeviceWaitIdle(device);

    destroyCaptureBuffer(device);
    m_capturePath.clear();
    m_captureRecorded = false;

    destroyImage(device, m_depthAov);
    destroyImage(device, m_overlayDepth);
    m_depthAovLayout = VK_IMAGE_LAYOUT_UNDEFINED;

    destroyGizmoBuffers(device);
    if (m_gizmoPipeline != VK_NULL_HANDLE) {
        vkDestroyPipeline(device, m_gizmoPipeline, nullptr);
        m_gizmoPipeline = VK_NULL_HANDLE;
    }
    if (m_gizmoPipelineLayout != VK_NULL_HANDLE) {
        vkDestroyPipelineLayout(device, m_gizmoPipelineLayout, nullptr);
        m_gizmoPipelineLayout = VK_NULL_HANDLE;
    }
    if (m_gridPipeline != VK_NULL_HANDLE) {
        vkDestroyPipeline(device, m_gridPipeline, nullptr);
        m_gridPipeline = VK_NULL_HANDLE;
    }
    if (m_gridPipelineLayout != VK_NULL_HANDLE) {
        vkDestroyPipelineLayout(device, m_gridPipelineLayout, nullptr);
        m_gridPipelineLayout = VK_NULL_HANDLE;
    }
    if (m_descriptorPool != VK_NULL_HANDLE) {
        vkDestroyDescriptorPool(device, m_descriptorPool, nullptr);
        m_descriptorPool = VK_NULL_HANDLE;
        m_descriptorSet = VK_NULL_HANDLE;
    }
    if (m_descriptorSetLayout != VK_NULL_HANDLE) {
        vkDestroyDescriptorSetLayout(device, m_descriptorSetLayout, nullptr);
        m_descriptorSetLayout = VK_NULL_HANDLE;
    }
    if (m_nearestSampler != VK_NULL_HANDLE) {
        vkDestroySampler(device, m_nearestSampler, nullptr);
        m_nearestSampler = VK_NULL_HANDLE;
    }
    m_staticReady = false;
    m_vkCmdBeginRendering = nullptr;
    m_vkCmdEndRendering = nullptr;
}

}  // namespace vkview
