#include "OverlayRenderer.hpp"

#include <renderer/ExternalRenderContext.hpp>

#include <QVulkanWindow>
#include <QVulkanInstance>
#include <QtDebug>

// SPIR-V byte arrays generated by glslangValidator at build time (see the
// overlay-shader rules in CMakeLists.txt). No runtime file loading.
#include "overlay_shaders/grid_vert.h"
#include "overlay_shaders/grid_frag.h"

namespace vkview {

namespace {

// Push constants shared by the grid shaders; must match grid.frag's PC block
struct GridPushConstants {
    glm::vec4 camPosFov;      // xyz camera position, w tan(fovY/2)
    glm::vec4 forwardAspect;  // xyz forward, w aspect
    glm::vec4 rightAlpha;     // xyz right, w overall grid alpha
    glm::vec4 upPad;          // xyz up
};
static_assert(sizeof(GridPushConstants) == 64, "GridPushConstants size mismatch");

VkShaderModule createShaderModule(VkDevice device, const uint32_t* code, size_t bytes) {
    VkShaderModuleCreateInfo info{};
    info.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    info.codeSize = bytes;
    info.pCode = code;
    VkShaderModule module = VK_NULL_HANDLE;
    if (vkCreateShaderModule(device, &info, nullptr, &module) != VK_SUCCESS) {
        qWarning() << "OverlayRenderer: failed to create shader module";
    }
    return module;
}

uint32_t findMemoryType(VkPhysicalDevice physDevice, uint32_t typeBits,
                        VkMemoryPropertyFlags props) {
    VkPhysicalDeviceMemoryProperties memProps;
    vkGetPhysicalDeviceMemoryProperties(physDevice, &memProps);
    for (uint32_t i = 0; i < memProps.memoryTypeCount; ++i) {
        if ((typeBits & (1u << i)) &&
            (memProps.memoryTypes[i].propertyFlags & props) == props) {
            return i;
        }
    }
    return 0;
}

}  // namespace

void OverlayRenderer::record(QVulkanWindow* window,
                             quantiloom::ExternalRenderContext* ctx,
                             VkCommandBuffer cmd,
                             uint32_t width, uint32_t height,
                             const CameraMatrices& camera) {
    if (!m_gridVisible || !ctx || width == 0 || height == 0) {
        return;  // nothing composited: leave the SDK's PRESENT_SRC frame alone
    }

    ensureStaticResources(window);
    if (m_gridPipeline == VK_NULL_HANDLE) {
        return;
    }
    ensureSizedResources(window, cmd, width, height);

    // 1. Pull the primary-hit depth into our sampled image
    ctx->BlitDepthTo(cmd, m_depthAov.image, m_depthAovLayout, width, height);
    m_depthAovLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;

    // 2. The SDK left the swapchain image in PRESENT_SRC; make it a color
    //    attachment again
    const int swapIndex = window->currentSwapChainImageIndex();
    VkImage swapImage = window->swapChainImage(swapIndex);
    VkImageView swapView = window->swapChainImageView(swapIndex);

    VkImageMemoryBarrier toColor{};
    toColor.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
    toColor.oldLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
    toColor.newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    toColor.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    toColor.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    toColor.image = swapImage;
    toColor.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    toColor.subresourceRange.levelCount = 1;
    toColor.subresourceRange.layerCount = 1;
    toColor.srcAccessMask = 0;  // the SDK's own barrier made the blit available
    toColor.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_READ_BIT |
                            VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                         VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT, 0,
                         0, nullptr, 0, nullptr, 1, &toColor);

    // 3. Dynamic rendering over the existing frame
    VkRenderingAttachmentInfoKHR colorAttachment{};
    colorAttachment.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO_KHR;
    colorAttachment.imageView = swapView;
    colorAttachment.imageLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    colorAttachment.loadOp = VK_ATTACHMENT_LOAD_OP_LOAD;  // never clear the frame
    colorAttachment.storeOp = VK_ATTACHMENT_STORE_OP_STORE;

    VkRenderingAttachmentInfoKHR depthAttachment{};
    depthAttachment.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO_KHR;
    depthAttachment.imageView = m_overlayDepth.view;
    depthAttachment.imageLayout = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL;
    depthAttachment.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;  // overlay-only depth
    depthAttachment.storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    depthAttachment.clearValue.depthStencil = {1.0f, 0};

    VkRenderingInfoKHR renderingInfo{};
    renderingInfo.sType = VK_STRUCTURE_TYPE_RENDERING_INFO_KHR;
    renderingInfo.renderArea = {{0, 0}, {width, height}};
    renderingInfo.layerCount = 1;
    renderingInfo.colorAttachmentCount = 1;
    renderingInfo.pColorAttachments = &colorAttachment;
    renderingInfo.pDepthAttachment = &depthAttachment;

    m_vkCmdBeginRendering(cmd, &renderingInfo);

    VkViewport viewport{0.0f, 0.0f, static_cast<float>(width),
                        static_cast<float>(height), 0.0f, 1.0f};
    VkRect2D scissor{{0, 0}, {width, height}};
    vkCmdSetViewport(cmd, 0, 1, &viewport);
    vkCmdSetScissor(cmd, 0, 1, &scissor);

    if (m_gridVisible) {
        GridPushConstants pc{};
        pc.camPosFov = glm::vec4(camera.position(), camera.fovScale());
        pc.forwardAspect = glm::vec4(camera.forward(), camera.aspect());
        pc.rightAlpha = glm::vec4(camera.right(), 0.55f);
        pc.upPad = glm::vec4(camera.up(), 0.0f);

        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, m_gridPipeline);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS,
                                m_gridPipelineLayout, 0, 1, &m_descriptorSet,
                                0, nullptr);
        vkCmdPushConstants(cmd, m_gridPipelineLayout,
                           VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                           0, sizeof(pc), &pc);
        vkCmdDraw(cmd, 3, 1, 0, 0);  // fullscreen triangle, no vertex buffer
    }

    m_vkCmdEndRendering(cmd);

    // 4. Back to PRESENT_SRC for Qt's present
    VkImageMemoryBarrier toPresent = toColor;
    toPresent.oldLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    toPresent.newLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
    toPresent.srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    toPresent.dstAccessMask = 0;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
                         VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, 0,
                         0, nullptr, 0, nullptr, 1, &toPresent);
}

void OverlayRenderer::ensureStaticResources(QVulkanWindow* window) {
    const VkFormat colorFormat = window->colorFormat();
    if (m_staticReady && colorFormat == m_pipelineColorFormat) {
        return;
    }

    VkDevice device = window->device();

    if (!m_vkCmdBeginRendering) {
        auto load = [&](const char* khr, const char* core) {
            auto fn = vkGetDeviceProcAddr(device, khr);
            if (!fn) fn = vkGetDeviceProcAddr(device, core);
            return fn;
        };
        m_vkCmdBeginRendering = reinterpret_cast<PFN_vkCmdBeginRenderingKHR>(
            load("vkCmdBeginRenderingKHR", "vkCmdBeginRendering"));
        m_vkCmdEndRendering = reinterpret_cast<PFN_vkCmdEndRenderingKHR>(
            load("vkCmdEndRenderingKHR", "vkCmdEndRendering"));
        if (!m_vkCmdBeginRendering || !m_vkCmdEndRendering) {
            qWarning() << "OverlayRenderer: dynamic rendering entry points missing";
            return;
        }
    }

    if (m_nearestSampler == VK_NULL_HANDLE) {
        // NEAREST on purpose: depth must never be bilinearly mixed across
        // silhouettes
        VkSamplerCreateInfo samplerInfo{};
        samplerInfo.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
        samplerInfo.magFilter = VK_FILTER_NEAREST;
        samplerInfo.minFilter = VK_FILTER_NEAREST;
        samplerInfo.addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
        samplerInfo.addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
        samplerInfo.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
        vkCreateSampler(device, &samplerInfo, nullptr, &m_nearestSampler);
    }

    if (m_descriptorSetLayout == VK_NULL_HANDLE) {
        VkDescriptorSetLayoutBinding binding{};
        binding.binding = 0;
        binding.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        binding.descriptorCount = 1;
        binding.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;

        VkDescriptorSetLayoutCreateInfo layoutInfo{};
        layoutInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
        layoutInfo.bindingCount = 1;
        layoutInfo.pBindings = &binding;
        vkCreateDescriptorSetLayout(device, &layoutInfo, nullptr, &m_descriptorSetLayout);

        VkDescriptorPoolSize poolSize{VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1};
        VkDescriptorPoolCreateInfo poolInfo{};
        poolInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
        poolInfo.poolSizeCount = 1;
        poolInfo.pPoolSizes = &poolSize;
        poolInfo.maxSets = 1;
        vkCreateDescriptorPool(device, &poolInfo, nullptr, &m_descriptorPool);

        VkDescriptorSetAllocateInfo allocInfo{};
        allocInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
        allocInfo.descriptorPool = m_descriptorPool;
        allocInfo.descriptorSetCount = 1;
        allocInfo.pSetLayouts = &m_descriptorSetLayout;
        vkAllocateDescriptorSets(device, &allocInfo, &m_descriptorSet);
    }

    createGridPipeline(window, colorFormat);
    m_pipelineColorFormat = colorFormat;
    m_staticReady = true;
}

void OverlayRenderer::createGridPipeline(QVulkanWindow* window, VkFormat colorFormat) {
    VkDevice device = window->device();

    if (m_gridPipeline != VK_NULL_HANDLE) {
        vkDestroyPipeline(device, m_gridPipeline, nullptr);
        m_gridPipeline = VK_NULL_HANDLE;
    }

    if (m_gridPipelineLayout == VK_NULL_HANDLE) {
        VkPushConstantRange pushRange{};
        pushRange.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
        pushRange.size = sizeof(GridPushConstants);

        VkPipelineLayoutCreateInfo layoutInfo{};
        layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
        layoutInfo.setLayoutCount = 1;
        layoutInfo.pSetLayouts = &m_descriptorSetLayout;
        layoutInfo.pushConstantRangeCount = 1;
        layoutInfo.pPushConstantRanges = &pushRange;
        vkCreatePipelineLayout(device, &layoutInfo, nullptr, &m_gridPipelineLayout);
    }

    VkShaderModule vertModule =
        createShaderModule(device, kGridVertSpv, sizeof(kGridVertSpv));
    VkShaderModule fragModule =
        createShaderModule(device, kGridFragSpv, sizeof(kGridFragSpv));
    if (vertModule == VK_NULL_HANDLE || fragModule == VK_NULL_HANDLE) {
        return;
    }

    VkPipelineShaderStageCreateInfo stages[2]{};
    stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vertModule;
    stages[0].pName = "main";
    stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = fragModule;
    stages[1].pName = "main";

    VkPipelineVertexInputStateCreateInfo vertexInput{};
    vertexInput.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;

    VkPipelineInputAssemblyStateCreateInfo inputAssembly{};
    inputAssembly.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    inputAssembly.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

    VkPipelineViewportStateCreateInfo viewportState{};
    viewportState.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    viewportState.viewportCount = 1;
    viewportState.scissorCount = 1;

    VkPipelineRasterizationStateCreateInfo raster{};
    raster.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    raster.polygonMode = VK_POLYGON_MODE_FILL;
    raster.cullMode = VK_CULL_MODE_NONE;
    raster.lineWidth = 1.0f;

    VkPipelineMultisampleStateCreateInfo multisample{};
    multisample.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    multisample.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    // Grid ignores raster depth entirely: occlusion by the scene happens in
    // the fragment shader against the depth AOV, and the gizmo drawn after it
    // always covers it (the overlay depth was just cleared).
    VkPipelineDepthStencilStateCreateInfo depthStencil{};
    depthStencil.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
    depthStencil.depthTestEnable = VK_FALSE;
    depthStencil.depthWriteEnable = VK_FALSE;

    VkPipelineColorBlendAttachmentState blendAttachment{};
    blendAttachment.blendEnable = VK_TRUE;
    blendAttachment.srcColorBlendFactor = VK_BLEND_FACTOR_SRC_ALPHA;
    blendAttachment.dstColorBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
    blendAttachment.colorBlendOp = VK_BLEND_OP_ADD;
    blendAttachment.srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
    blendAttachment.dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
    blendAttachment.alphaBlendOp = VK_BLEND_OP_ADD;
    blendAttachment.colorWriteMask =
        VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
        VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;

    VkPipelineColorBlendStateCreateInfo blend{};
    blend.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    blend.attachmentCount = 1;
    blend.pAttachments = &blendAttachment;

    const VkDynamicState dynamicStates[] = {VK_DYNAMIC_STATE_VIEWPORT,
                                            VK_DYNAMIC_STATE_SCISSOR};
    VkPipelineDynamicStateCreateInfo dynamic{};
    dynamic.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    dynamic.dynamicStateCount = 2;
    dynamic.pDynamicStates = dynamicStates;

    VkPipelineRenderingCreateInfoKHR rendering{};
    rendering.sType = VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO_KHR;
    rendering.colorAttachmentCount = 1;
    rendering.pColorAttachmentFormats = &colorFormat;
    rendering.depthAttachmentFormat = VK_FORMAT_D32_SFLOAT;

    VkGraphicsPipelineCreateInfo pipelineInfo{};
    pipelineInfo.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    pipelineInfo.pNext = &rendering;
    pipelineInfo.stageCount = 2;
    pipelineInfo.pStages = stages;
    pipelineInfo.pVertexInputState = &vertexInput;
    pipelineInfo.pInputAssemblyState = &inputAssembly;
    pipelineInfo.pViewportState = &viewportState;
    pipelineInfo.pRasterizationState = &raster;
    pipelineInfo.pMultisampleState = &multisample;
    pipelineInfo.pDepthStencilState = &depthStencil;
    pipelineInfo.pColorBlendState = &blend;
    pipelineInfo.pDynamicState = &dynamic;
    pipelineInfo.layout = m_gridPipelineLayout;

    if (vkCreateGraphicsPipelines(device, VK_NULL_HANDLE, 1, &pipelineInfo,
                                  nullptr, &m_gridPipeline) != VK_SUCCESS) {
        qWarning() << "OverlayRenderer: failed to create grid pipeline";
        m_gridPipeline = VK_NULL_HANDLE;
    }

    vkDestroyShaderModule(device, vertModule, nullptr);
    vkDestroyShaderModule(device, fragModule, nullptr);
}

void OverlayRenderer::ensureSizedResources(QVulkanWindow* window, VkCommandBuffer cmd,
                                           uint32_t width, uint32_t height) {
    VkDevice device = window->device();

    if (m_depthAov.width != width || m_depthAov.height != height) {
        destroyImage(device, m_depthAov);
        m_depthAov = createImage(window, width, height, VK_FORMAT_R32_SFLOAT,
                                 VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT,
                                 VK_IMAGE_ASPECT_COLOR_BIT);
        m_depthAovLayout = VK_IMAGE_LAYOUT_UNDEFINED;

        VkDescriptorImageInfo imageInfo{};
        imageInfo.sampler = m_nearestSampler;
        imageInfo.imageView = m_depthAov.view;
        imageInfo.imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;

        VkWriteDescriptorSet write{};
        write.sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        write.dstSet = m_descriptorSet;
        write.dstBinding = 0;
        write.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        write.descriptorCount = 1;
        write.pImageInfo = &imageInfo;
        vkUpdateDescriptorSets(device, 1, &write, 0, nullptr);
    }

    if (m_overlayDepth.width != width || m_overlayDepth.height != height) {
        destroyImage(device, m_overlayDepth);
        m_overlayDepth = createImage(window, width, height, VK_FORMAT_D32_SFLOAT,
                                     VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT,
                                     VK_IMAGE_ASPECT_DEPTH_BIT);
        m_overlayDepthInitialized = false;
    }

    if (!m_overlayDepthInitialized) {
        VkImageMemoryBarrier toDepth{};
        toDepth.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
        toDepth.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        toDepth.newLayout = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL;
        toDepth.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        toDepth.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        toDepth.image = m_overlayDepth.image;
        toDepth.subresourceRange.aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT;
        toDepth.subresourceRange.levelCount = 1;
        toDepth.subresourceRange.layerCount = 1;
        toDepth.srcAccessMask = 0;
        toDepth.dstAccessMask = VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT |
                                VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                             VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT |
                                 VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT,
                             0, 0, nullptr, 0, nullptr, 1, &toDepth);
        m_overlayDepthInitialized = true;
    }
}

OverlayRenderer::OwnedImage OverlayRenderer::createImage(
    QVulkanWindow* window, uint32_t width, uint32_t height, VkFormat format,
    VkImageUsageFlags usage, VkImageAspectFlags aspect) {
    VkDevice device = window->device();
    OwnedImage img;
    img.width = width;
    img.height = height;

    VkImageCreateInfo imageInfo{};
    imageInfo.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    imageInfo.imageType = VK_IMAGE_TYPE_2D;
    imageInfo.format = format;
    imageInfo.extent = {width, height, 1};
    imageInfo.mipLevels = 1;
    imageInfo.arrayLayers = 1;
    imageInfo.samples = VK_SAMPLE_COUNT_1_BIT;
    imageInfo.tiling = VK_IMAGE_TILING_OPTIMAL;
    imageInfo.usage = usage;
    if (vkCreateImage(device, &imageInfo, nullptr, &img.image) != VK_SUCCESS) {
        qWarning() << "OverlayRenderer: failed to create image";
        return img;
    }

    VkMemoryRequirements memReq;
    vkGetImageMemoryRequirements(device, img.image, &memReq);
    VkMemoryAllocateInfo allocInfo{};
    allocInfo.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    allocInfo.allocationSize = memReq.size;
    allocInfo.memoryTypeIndex = findMemoryType(window->physicalDevice(),
                                               memReq.memoryTypeBits,
                                               VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (vkAllocateMemory(device, &allocInfo, nullptr, &img.memory) != VK_SUCCESS ||
        vkBindImageMemory(device, img.image, img.memory, 0) != VK_SUCCESS) {
        qWarning() << "OverlayRenderer: failed to allocate image memory";
        destroyImage(device, img);
        return img;
    }

    VkImageViewCreateInfo viewInfo{};
    viewInfo.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    viewInfo.image = img.image;
    viewInfo.viewType = VK_IMAGE_VIEW_TYPE_2D;
    viewInfo.format = format;
    viewInfo.subresourceRange.aspectMask = aspect;
    viewInfo.subresourceRange.levelCount = 1;
    viewInfo.subresourceRange.layerCount = 1;
    if (vkCreateImageView(device, &viewInfo, nullptr, &img.view) != VK_SUCCESS) {
        qWarning() << "OverlayRenderer: failed to create image view";
        destroyImage(device, img);
    }
    return img;
}

void OverlayRenderer::destroyImage(VkDevice device, OwnedImage& img) {
    if (img.view != VK_NULL_HANDLE) vkDestroyImageView(device, img.view, nullptr);
    if (img.image != VK_NULL_HANDLE) vkDestroyImage(device, img.image, nullptr);
    if (img.memory != VK_NULL_HANDLE) vkFreeMemory(device, img.memory, nullptr);
    img = OwnedImage{};
}

void OverlayRenderer::releaseResources(QVulkanWindow* window) {
    VkDevice device = window->device();
    if (device == VK_NULL_HANDLE) {
        return;
    }
    vkDeviceWaitIdle(device);

    destroyImage(device, m_depthAov);
    destroyImage(device, m_overlayDepth);
    m_depthAovLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    m_overlayDepthInitialized = false;

    if (m_gridPipeline != VK_NULL_HANDLE) {
        vkDestroyPipeline(device, m_gridPipeline, nullptr);
        m_gridPipeline = VK_NULL_HANDLE;
    }
    if (m_gridPipelineLayout != VK_NULL_HANDLE) {
        vkDestroyPipelineLayout(device, m_gridPipelineLayout, nullptr);
        m_gridPipelineLayout = VK_NULL_HANDLE;
    }
    if (m_descriptorPool != VK_NULL_HANDLE) {
        vkDestroyDescriptorPool(device, m_descriptorPool, nullptr);
        m_descriptorPool = VK_NULL_HANDLE;
        m_descriptorSet = VK_NULL_HANDLE;
    }
    if (m_descriptorSetLayout != VK_NULL_HANDLE) {
        vkDestroyDescriptorSetLayout(device, m_descriptorSetLayout, nullptr);
        m_descriptorSetLayout = VK_NULL_HANDLE;
    }
    if (m_nearestSampler != VK_NULL_HANDLE) {
        vkDestroySampler(device, m_nearestSampler, nullptr);
        m_nearestSampler = VK_NULL_HANDLE;
    }
    m_staticReady = false;
    m_vkCmdBeginRendering = nullptr;
    m_vkCmdEndRendering = nullptr;
}

}  // namespace vkview
